---
version: 0.0.1

build_arg_defaults:
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:latest
#  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:1.0.0-147
  EE_BUILDER_IMAGE: registry.redhat.io/ansible-automation-platform-22/ansible-builder-rhel8:latest
#  EE_BUILDER_IMAGE: registry.redhat.io/ansible-automation-platform-22/ansible-builder-rhel8:1.1.0-77

#ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: 
    - COPY krb5.conf /etc/krb5.conf  


#RUN pip3 install --upgrade pip setuptools wheel
#        RUN /usr/bin/python3 -m pip3 install --upgrade pip setuptools
#
#  append:
#    - RUN ls -la /
