---
- hosts: "{{ HOSTS }}"
  tasks:
  - name: Copy required packages
    copy:
      src: jdk-8u181-linux-x64.tar
      dest: /opt
  - name: Untar jdk
    shell: tar -xvf /opt/jdk-8u181-linux-x64.tar
  - name:  Install java
    shell: |
      alternatives --install /usr/bin/java java /opt/jdk1.8.0_181/bin/java 2
      alternatives --install /usr/bin/jar jar /opt/jdk1.8.0_181/bin/jar 2
      alternatives --install /usr/bin/javac javac /opt/jdk1.8.0_181/bin/javac 2
      alternatives --set jar /opt/jdk1.8.0_181/bin/jar
      alternatives --set javac /opt/jdk1.8.0_181/bin/javac
      echo 2 | alternatives --config java
    





